[package]
name = "rhino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.28.4"
nvml-wrapper = "0.9.0"
winapi = "0.2.8"
kernel32-sys = "0.2.1"
